language: scala

# Cache dependencies:
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

# Cleanup the cached directories to avoid unnecessary cache updates
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# One build job per bug report:
matrix:
  include:
    - name: indirect-valueof
      script:
        - cd indirect-valueof
        - sbt compile
    - name: infinite-loop-match-types
      script:
        - cd infinite-loop-match-types
        - sbt compile
    - name: match-types-recursion-limit
      script:
        - cd match-types-recursion-limit
        - sbt compile
